"""
Render a corrected DataFrame to a branded, print-ready PDF.

Matches the NgineAgent / engine.usesmpt.com house style (ink + teal palette,
letterhead header band, metadata strip, styled table, numbered footer) so the
engine's export looks like the Proof Pack rather than a bare table dump.

Uses reportlab (pure-Python, no system dependencies) so it renders per-request
on the VPS without a headless browser.
"""

import io
from datetime import datetime, timezone

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_RIGHT
from reportlab.platypus import (
    BaseDocTemplate,
    PageTemplate,
    Frame,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
)


# ── House palette (from Engine Proof Pack) ───────────────────────────────────
INK = colors.HexColor("#0c1a1f")
TEAL = colors.HexColor("#0fb89c")
TEAL_DK = colors.HexColor("#0b6f5e")
AMBER = colors.HexColor("#d9892a")
MUTED = colors.HexColor("#6b7b80")
ZEBRA = colors.HexColor("#f3f4f6")
GRIDC = colors.HexColor("#d7dee0")

# Cells longer than this are truncated so wide catalogs stay readable.
_MAX_CELL_CHARS = 48

_BRAND = "NgineAgent"
_URL = "engine.usesmpt.com"


def _stringify(value) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    text = str(value)
    if len(text) > _MAX_CELL_CHARS:
        return text[: _MAX_CELL_CHARS - 1] + "…"
    return text


class _NumberedCanvas:
    """Two-pass canvas wrapper so the footer can show 'Page X of Y'."""

    def __init__(self, header_title: str, subtitle: str):
        self.header_title = header_title
        self.subtitle = subtitle

    def __call__(self, canvas, doc):
        # store this page's state, draw chrome at save time when total is known
        canvas._saved_page_states = getattr(canvas, "_saved_page_states", [])
        self._draw(canvas, doc)

    def _draw(self, canvas, doc):
        w, h = doc.pagesize

        # ── Header band ──────────────────────────────────────────────────
        band_h = 0.62 * inch
        canvas.setFillColor(INK)
        canvas.rect(0, h - band_h, w, band_h, stroke=0, fill=1)
        # teal accent rule under the band
        canvas.setFillColor(TEAL)
        canvas.rect(0, h - band_h - 3, w, 3, stroke=0, fill=1)

        # engine mark (teal dot)
        cx, cy = 0.5 * inch, h - band_h / 2
        canvas.setFillColor(TEAL)
        canvas.circle(cx, cy, 9, stroke=0, fill=1)
        canvas.setFillColor(TEAL_DK)
        canvas.circle(cx + 2.5, cy - 2.5, 4.5, stroke=0, fill=1)

        # title + subtitle
        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 14)
        canvas.drawString(0.78 * inch, cy - 1, self.header_title)
        canvas.setFillColor(TEAL)
        canvas.setFont("Helvetica", 9)
        canvas.drawRightString(w - 0.5 * inch, cy + 4, _URL)
        canvas.setFillColor(MUTED)
        canvas.setFont("Helvetica", 7.5)
        canvas.drawRightString(w - 0.5 * inch, cy - 7, self.subtitle)

        # ── Footer ───────────────────────────────────────────────────────
        canvas.setStrokeColor(GRIDC)
        canvas.setLineWidth(0.5)
        canvas.line(0.5 * inch, 0.5 * inch, w - 0.5 * inch, 0.5 * inch)
        canvas.setFillColor(MUTED)
        canvas.setFont("Helvetica", 7.5)
        canvas.drawString(0.5 * inch, 0.36 * inch, f"Generated by {_BRAND} · {_URL}")
        page_num = canvas.getPageNumber()
        canvas.drawRightString(w - 0.5 * inch, 0.36 * inch, f"Page {page_num}")


def export_pdf(df: pd.DataFrame, title: str = "Corrected Data Export", domain: str | None = None) -> bytes:
    buf = io.BytesIO()

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    subtitle = f"Corrected dataset · {generated}"
    if domain:
        subtitle = f"{domain} domain · {generated}"

    doc = BaseDocTemplate(
        buf,
        pagesize=landscape(letter),
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
        topMargin=0.95 * inch,   # clear the header band
        bottomMargin=0.7 * inch,
        title=title,
        author=_BRAND,
    )
    frame = Frame(
        doc.leftMargin,
        doc.bottomMargin,
        doc.width,
        doc.height,
        id="body",
    )
    painter = _NumberedCanvas(title, subtitle)
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=painter)])

    styles = getSampleStyleSheet()
    meta_style = ParagraphStyle(
        "meta", parent=styles["Normal"], fontSize=9, textColor=MUTED, spaceAfter=2
    )
    accent_style = ParagraphStyle(
        "accent", parent=styles["Normal"], fontSize=9, textColor=TEAL_DK,
        fontName="Helvetica-Bold", alignment=TA_RIGHT,
    )

    elements = [
        Paragraph(
            f"<b>{len(df)}</b> rows &nbsp;×&nbsp; <b>{len(df.columns)}</b> columns",
            meta_style,
        ),
        Spacer(1, 0.12 * inch),
    ]

    header = [_stringify(c) for c in df.columns]
    rows = [[_stringify(v) for v in row] for row in df.itertuples(index=False, name=None)]
    data = [header] + rows if rows else [header, ["(no rows)"] + [""] * (len(header) - 1)]

    n_cols = max(len(header), 1)
    font_size = 8 if n_cols <= 8 else 7 if n_cols <= 14 else 6

    table = Table(data, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                # header row
                ("BACKGROUND", (0, 0), (-1, 0), INK),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("LINEBELOW", (0, 0), (-1, 0), 1.2, TEAL),
                # body
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), font_size),
                ("TEXTCOLOR", (0, 1), (-1, -1), INK),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ZEBRA]),
                ("GRID", (0, 0), (-1, -1), 0.25, GRIDC),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    elements.append(table)

    doc.build(elements)
    return buf.getvalue()
